/*

@license
dhtmlxScheduler v.5.3.10 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) XB Software Ltd.

*/
Scheduler.plugin(function(e){(function(){e.config.all_timed="short";e.config.all_timed_month=false;var t=function(t){if(!((t.end_date-t.start_date)/(1e3*60*60)>=24)){return true}if(e._drag_mode=="resize"&&e._drag_id==t.id){return true}return false};e._safe_copy=function(t){var a=null,i=e._copy_event(t);if(t.event_pid){a=e.getEvent(t.event_pid)}if(a&&a.isPrototypeOf(t)){delete i.event_length;delete i.event_pid;delete i.rec_pattern;delete i.rec_type}return i};var a=e._pre_render_events_line;var i=e._pre_render_events_table;var n=function(e,t){if(!this._table_view){return a.call(this,e,t)}return i.call(this,e,t)};e._pre_render_events_line=e._pre_render_events_table=function(a,i){if(!this.config.all_timed||this._table_view&&this._mode!="month"||this._mode=="month"&&!this.config.all_timed_month)return n.call(this,a,i);for(var _=0;_<a.length;_++){var r=a[_];if(r._timed)continue;if(this.config.all_timed=="short"){if(!t(r)){if(this._mode!="month"){a.splice(_--,1)}continue}}var d=this._safe_copy(r);if(!r._virtual){d._first_chunk=true}else{d._first_chunk=false}d._drag_resize=false;d._virtual=true;d.start_date=new Date(d.start_date);if(!u(r)){d.end_date=new Date(r.end_date)}else{d.end_date=o(d.start_date);if(this.config.last_hour!=24){d.end_date=c(d.start_date,this.config.last_hour)}}var s=false;if(d.start_date<this._max_date&&d.end_date>this._min_date&&d.start_date<d.end_date){a[_]=d;s=true}var l=this._safe_copy(r);l._virtual=true;l.end_date=new Date(l.end_date);if(l.start_date<this._min_date)l.start_date=c(this._min_date,this.config.first_hour);else l.start_date=c(o(r.start_date),this.config.first_hour);if(l.start_date<this._max_date&&l.start_date<l.end_date){if(s){a.splice(_+1,0,l)}else{a[_--]=l;continue}l._last_chunk=false}else{d._last_chunk=true;d._drag_resize=true}}var f=this._drag_mode=="move"?false:i;return n.call(this,a,f);function u(e){var t=o(e.start_date);return+e.end_date>+t}function o(t){var a=e.date.add(t,1,"day");a=e.date.date_part(a);return a}function c(t,a){var i=e.date.date_part(new Date(t));i.setHours(a);return i}};var _=e.get_visible_events;e.get_visible_events=function(e){if(!(this.config.all_timed&&this.config.multi_day))return _.call(this,e);return _.call(this,false)};e.attachEvent("onBeforeViewChange",function(t,a,i,n){e._allow_dnd=i=="day"||i=="week";return true});e._is_main_area_event=function(e){return!!(e._timed||this.config.all_timed===true||this.config.all_timed=="short"&&t(e))};var r=e.updateEvent;e.updateEvent=function(t){var a=e.getEvent(t);var i;var n;if(a){i=e.config.all_timed&&!(e.isOneDayEvent(e._events[t])||e.getState().drag_id);if(i){n=e.config.update_render;e.config.update_render=true}}r.apply(e,arguments);if(a){if(i){e.config.update_render=n}}}})()});